### ISSUE TITLE
Bug: Daemon stops responding to all requests

### ISSUE THREAD

**Issue by juligasa** [seed-hypermedia/seed#19]
## Problem

After getting a document the daemon stops responding. The document has two parent documents. 

## Steps to Reproduce

getting this testnet document https://test.hyper.media/hm/z6MkkVED4zEYbWS7Wy2mhojtc3EXc6YfPbpy8Xzgxktvy1z3/demo-subdocument/this-is-the-one?v=bafy2bzacear4k7aptdtula4hddtdkfxgyqld2olavsptfyxenfvxg3blms6ng

first the discover request gives: [unknown] No providers found for CID bafkqavtinu5c6l32gzgww22wivcdi6sflfrfouzxk54te3lin5vhiyztivmggnszmzige4dzhbmhuz3ynn2hm6jrpizs6zdfnvxs243vmjsg6y3vnvsw45bporugs4znnfzs25dimuww63tf
then after retry discover a few times, every request to daemon starts breaking

**Comment by burdiyan** [comment]
Fixed I guess after fixing db conn leak? @juligasa 

Reopen if still relevant
