### ISSUE TITLE
Bug: Cursor Does Not Change to Hand When Navigating Documents (Desktop App)

### ISSUE THREAD

**Issue by SalvaZaraes** [seed-hypermedia/seed#50]
Description:
In the desktop app, when switching between documents in the top row (in the "newspaper view"), the cursor does not change from the standard pointer to a hand icon when hovering over document names. This makes it difficult to know if clicking will navigate to the document.

Steps to Reproduce:
Open the desktop app and navigate to the top document view.
Hover over document names and observe the cursor behavior.

Expected Behavior:
The cursor should change to a hand icon when hovering over clickable document names.

**Comment by ericvicenti** [comment]
Yes we have been experimenting with this intentionally!

I think the "hand" cursor should probably be used for all links, like you say here, but not button presses

**Comment by SalvaZaraes** [comment]
Ok, great!
