### ISSUE TITLE
Bug: "+" Menu Block Not Fully Visible at Screen Edges (Desktop App)

### ISSUE THREAD

**Issue by SalvaZaraes** [seed-hypermedia/seed#51]
Description:
When editing a document in the desktop app, clicking the "+" button to add a block near the top or bottom of the window causes the menu to be partially cut off. The same issue occurs when selecting the programming language for a code block, limiting visibility of the options.

Steps to Reproduce:
Edit a document and click the "+" button near the screen’s top or bottom.
Observe the visibility of the menu.

Expected Behavior:
The entire menu should be fully visible, even when accessed near the edges of the screen.

**Comment by horacioh** [comment]
https://github.com/user-attachments/assets/c5e9748d-301a-4588-822f-85cac4c03d5c
fixed!
