### ISSUE TITLE
Bug: Delete document does not work

### ISSUE THREAD

**Issue by jjsalasrivera** [seed-hypermedia/seed#60]
## Problem

In mac desktop app, when you want to delete and block a document, the button seems to not work. Document isn't deleted and the modal message does not close. 

## Steps to Reproduce

- Create a document.
- publish
- open document
- push button delete publication in the top right menu
- Appears a windows, fill the comment and push Delete + block.

## Expected Behavior

Expect that de document dissapear from my tree.

**Comment by horacioh** [comment]
hey @jjsalasrivera !

this is fixed on the latest version of the Seed app 2024.11.8!
you can download it on the [Releases page](https://github.com/seed-hypermedia/seed/releases/tag/2024.11.8)
